export const GOVT_START_DATE = new Date('2026-05-11');

export const CATEGORY_LABELS: Record<string, string> = {
  alcohol_menace: 'Alcohol Menace',
  attack_on_press: 'Attack on Press',
  censorship: 'Censorship',
  children: 'Children',
  communal_violence: 'Communal Violence',
  corruption: 'Corruption',
  credit_stealing: 'Credit Stealing',
  crime_law: 'Crime / Law',
  crimes_women_kids: 'Crimes vs Women & Kids',
  custodial_death: 'Custodial Death',
  dalits: 'Dalits',
  drug_menace: 'Drug Menace',
  eb_failure: 'EB Failure',
  extortion: 'Extortion',
  fact_check: 'Fact Check',
  fake_news: 'Fake News',
  fake_image: 'Fake Image / AI',
  gov_inspection: 'Gov Inspection',
  governance: 'Governance',
  honour_killing: 'Honour Killing',
  industrial_flight: 'Industrial Flight',
  language_imposition: 'Language Imposition',
  media_blackout: 'Media Blackout',
  media_corruption: 'Media Corruption',
  mineral_smuggling: 'Mineral Smuggling',
  murders: 'Murders',
  paid_media: 'Paid Media',
  police_excess: 'Police Excess',
  poll_promises: 'Poll Promises',
  power_cut: 'Power Cut',
  propaganda: 'Propaganda',
  reels: 'Reels',
  sexual_assault: 'Sexual Assaults',
  stickers: 'Stickers',
  tenders: 'Tenders / Scams',
  theft: 'Theft',
  violence: 'Violence',
  water_shortage: 'Water Shortage',
  other: 'Other',
};

export const CATEGORY_COLORS: Record<string, string> = {
  corruption: 'text-yellow-400 border-yellow-400',
  murders: 'text-red-500 border-red-500',
  sexual_assault: 'text-red-400 border-red-400',
  crimes_women_kids: 'text-orange-400 border-orange-400',
  censorship: 'text-purple-400 border-purple-400',
  credit_stealing: 'text-blue-400 border-blue-400',
  governance: 'text-gray-400 border-gray-400',
  police_excess: 'text-red-300 border-red-300',
  drug_menace: 'text-green-400 border-green-400',
  media_blackout: 'text-purple-300 border-purple-300',
  tenders: 'text-yellow-300 border-yellow-300',
  fake_news: 'text-pink-400 border-pink-400',
  alcohol_menace: 'text-amber-400 border-amber-400',
  other: 'text-gray-500 border-gray-500',
};

export const PROMISE_STATUS_COLORS: Record<string, string> = {
  pending: 'bg-gray-700 text-gray-300',
  kept: 'bg-green-900 text-green-300',
  broken: 'bg-red-900 text-red-300',
  partial: 'bg-yellow-900 text-yellow-300',
};
