/**
 * The full academic bibliography underpinning the Dravidian Model analysis —
 * transcribed from the reference list of Kalaiyarasan A. & M. Vijayabaskar,
 * "The Dravidian Model: Interpreting the Political Economy of Tamil Nadu"
 * (Cambridge University Press, 2021), the foundational scholarly work on TN's
 * political economy. ~300 peer-reviewed sources. "———" denotes a repeated
 * author from the entry above (standard bibliography convention).
 */
export const BIBLIOGRAPHY: string[] = [
  `Abegaz, B. 2013. 'Political Parties in Business: Rent Seekers, Developmentalists, or Both?' Journal of Development Studies 49(11): 1467–83.`,
  `Abraham, V. 2016. 'MGNREGS: Political Economy, Local Governance and Asset Creation in South India' (CDS Working Paper No. 471). Centre for Development Studies.`,
  `Acharya, D., G. Vaidyanathan, V. R. Muraleedharan, D. S. Dheenadayalan and U. Dash. 2011. 'Do the Poor Benefit from Public Spending on Healthcare in India? Results from Benefit and (Utilisation) Incidence Analysis in Tamil Nadu and Orissa'. LSHTM.`,
  `Adiseshiah, M. 1972. The Perspective Plan for Tamil Nadu: Towards a Learning Society. Madras: State Planning Commission, Government of Tamil Nadu.`,
  `Agarwal, P. 2006. 'Higher Education in India: The Need for Change' (Working Paper No. 180). ICRIER.`,
  `Agarwala, R. 2013. Informal Labor, Formal Politics, and Dignified Discontents in India. Cambridge: Cambridge University Press.`,
  `Agarwala, R. and R. Herring. 2013. 'Does Class Matter in Politics?' In Interpreting Politics, edited by J. Echeverri-Gent and K. Sadiq. New Delhi: Oxford University Press.`,
  `Aglietta, M. 2000 [1979]. A Theory of Capitalist Regulation: The US Experience. London and New York: Verso.`,
  `Ahluwalia, M. S. 1978. 'Rural Poverty and Agricultural Performance in India'. The Journal of Development Studies 14(3): 298–323.`,
  `Alamu, R. 2011. 'It Just Works in TN'. The Hindu, 24 September.`,
  `Alcott, B. and P. Rose. 2017. 'Learning in India's Primary Schools: How Do Disparities Widen Across the Grades?' International Journal of Educational Development 56: 42–51.`,
  `Alexander, K. 2018. 'What Tamil Nadu, Kerala Can Teach Other States'. Livemint, 22 May.`,
  `Aloysius, G. 2013. Village Reconstruction. New Delhi: Critical Quest.`,
  `Amirapu, A. and A. Subramanian. 2015. 'Manufacturing or Services? An Indian Illustration of a Development Dilemma' (WP No. 408). Center for Global Development.`,
  `Amsden, A. 1989. Asia's Next Giant: South Korea and Late Industrialization. New York and Oxford: Oxford University Press.`,
  `Anaimuthu, V. 1974. Periyar Ee Ve Ra Sinthanaikal [Thoughts of Periyar E. V. R.] (3 Vols). Tiruchirapalli: Thinker's Forum.`,
  `Anandhi, S. 2018. 'Education and Dravidian Common Sense', Seminar, 708 (August).`,
  `———. 1991. 'Women's Question in the Dravidian Movement c. 1925–1948'. Social Scientist 19(5/6): 24–41.`,
  `Anandhi, S., K. R. Manoharan, M. Vijayabaskar and A. Kalaiyarasan (eds). 2020. Rethinking Social Justice. Hyderabad: Orient Blackswan.`,
  `Anandhi, S. and M. Vijayabaskar. 2013. 'Where Buying a Motorcycle Can Spark a Riot'. The Hindu.`,
  `Annadurai, C. N. 2017 [1949]. Panathottam [Garden of Money]. Chennai: Aazhi Publishers.`,
  `Anwar, S. 2018. 'Muslims and the Dravidian Movement'. Seminar, 708 (August).`,
  `Appadurai, A. 2004. 'The Capacity to Aspire: Culture and the Terms of Recognition'. In Culture and Public Action, edited by V. Rao and M. Walton. Stanford University Press.`,
  `Arasu, V. 2012. Madras Secular Society: Collected Articles from The Thinker (6 Vols). Chennai: New Century Book House.`,
  `———. 2013. Aththipakkam A. Venkatachalanaar akkangal. Chennai: New Century Book House.`,
  `Arooran, K. N. 1980. Tamil Renaissance and Dravidian Nationalism, 1905–1944. Madurai: Koodal Publishers.`,
  `Arora, R. U. 2009. 'Globalization and Stages of Development'. Review of Urban & Regional Development Studies 21(2/3): 124–42.`,
  `Asher, Sam, Paul Novosad and Charlie Rafkin. 2020. 'Intergenerational Mobility in India: New Methods and Estimates Across Time, Space, and Communities'.`,
  `Athreya, V. B., G. Boklin, G. Djurfeldt and S. Lindberg. 1986. 'Production Relations and Agrarian Change: Some Findings from a Case Study in Tamil Nadu'. Social Scientist 14(5): 3–14.`,
  `Audretsch, D. B., D. Heger and T. Veith. 2015. 'Infrastructure and Entrepreneurship'. Small Business Economics 44(2): 219–30.`,
  `Babu, Gireesh. 2020. 'Tamil Nadu Eyes Major Investments in State's Auto, Auto Components Industry'. Business Standard, 5 January.`,
  `Bagchi A. K. 2012. 'Indian Business History'. Indian Historical Review 39(1): 73–91.`,
  `Baker, C. J. 1976. The Politics of South India 1920–1937. New Delhi: Vikas Publishing House.`,
  `Balagopal, G. and M. Vijayabaskar. 2018. Vulnerability, State and Social Protection in Tamil Nadu: A Life-cycle Perspective. Report to UNICEF, Chennai.`,
  `———. 2019. 'Flaws of Insurance-based Healthcare Provision'. Economic & Political Weekly 54(2): 18–21.`,
  `Balagopal, K. 2009. 'Ideology and Adjudication: The Supreme Court and OBC Reservations'. Economic & Political Weekly 44(43): 16–19.`,
  `Balakrishnan, P. 2008. 'Visible Hand: Public Policy and Economic Growth in the Nehru Era'. The Indian Economic Journal 56(1): 11–35.`,
  `Balarajan, Y., S. Selvaraj and S. V. Subramanian. 2011. 'Health Care and Equity in India'. The Lancet 377(9764): 505–15.`,
  `Banerjee, S. and N. Ghosh. 2018. 'Introduction: Debating Intersectionalities'. South Asia Multidisciplinary Academic Journal, 19.`,
  `Banerjee, A. and L. Iyer. 2005. 'History, Institutions and Economic Performance: The Legacy of Colonial Land Tenure Systems in India'. American Economic Review 95(4): 1190–1213.`,
  `Bardhan, P. K. 1973. 'On the Incidence of Poverty in Rural India in the Sixties'. Economic & Political Weekly 8(4–6): 245–54.`,
  `Bardhan, P. 2008. 'Economic Reforms, Poverty, and Inequality in China and India'. In Arguments for a Better World, edited by K. Basu and R. Kanbur. Oxford University Press.`,
  `———. 2009. 'Notes on the Political Economy of India's Tortuous Transition'. Economic & Political Weekly 44(49): 31–36.`,
  `———. 2013. 'Inequality, Inefficiency, and the Challenges for Social Democracy in India's Economic Transition'. New Delhi: Academic Foundation.`,
  `Barnett, M. R. 1976. The Politics of Cultural Nationalism in South India. Princeton: Princeton University Press.`,
  `Barrientos, A. and D. Hulme. 2009. 'Social Protection for the Poor and Poorest in Developing Countries'. Oxford Development Studies 37(4): 439–56.`,
  `Basu, R. 2013. 'Leadership in the Health Sector: The Importance of the Tamil Nadu Model'. NAPSIPAG Conference, Dehradun.`,
  `Basu, K. and A. Maertens. 2007. 'Public Health in India'. In Oxford Companion to Economics in India, edited by K. Basu. Oxford University Press.`,
  `Benjamin, D., P. Winters, T. Reardon and K. Stamoulis. 2009. 'Rural Nonfarm Employment and Farming'. Agricultural Economics 40(2): 119–23.`,
  `Berman, P. and R. Ahuja. 2008. 'Government Health Spending in India'. Economic & Political Weekly 43(26–27): 209–16.`,
  `Bernstein, H. 1996. 'Agrarian Questions Then and Now'. Journal of Peasant Studies 24(1–2): 22–59.`,
  `Bhagwati, J. and A. Panagariya. 2013. Why Growth Matters. New York: PublicAffairs.`,
  `Bharadwaj, K. 1982. 'Regional Differentiation in India: A Note'. Economic & Political Weekly 17(14–16).`,
  `Bharathidasan, K. 2015. 'Political Biography of Rao Saheb L. C. Guruswamy (1895–1960)'. Presented at MIDS, Chennai.`,
  `Bhatnagar, R. 2011. 'More than 50% Engineering Colleges Are of Poor Quality: Government of Tamil Nadu'. Shiksha, 1 November.`,
  `Bonner, K. et al. 2012. MGNREGA Implementation: A Cross-state Comparison. Princeton: Princeton University Press.`,
  `Carswell, G. and G. De Neve. 2014. 'MGNREGA in Tamil Nadu: A Story of Success and Transformation?' Journal of Agrarian Change 14(4): 564–85.`,
  `Cassen, R. 1978. India: Population, Economy, Society. London: Macmillan.`,
  `Chakraborty, A. 2019. 'Inter-state Variations in Infrastructure and Social Service Delivery'. Institute for Human Development, New Delhi.`,
  `Chakraborty, P. 2019. 'Fiscal Federalism in India: Who Should Do What?' The India Forum, 8 July.`,
  `Chari, S. 2004. Fraternal Capital: Peasant-workers, Self-made Men, and Globalisation in Provincial India. Stanford University Press.`,
  `Chatterjee, P. 2004. The Politics of the Governed: Reflections on Popular Politics in Most of the World. New York: Columbia University Press.`,
  `———. 2008. 'Democracy and Economic Transformation in India'. Economic & Political Weekly 43(16): 53–62.`,
  `———. 2011. Lineages of Political Society: Studies in Postcolonial Democracy. New York: Columbia University Press.`,
  `———. 2013. 'Land and the Political Management of Primitive Accumulation'. In The Land Question in India. Oxford University Press.`,
  `———. 2014. I am the People: Reflections on Popular Sovereignty Today. New York: Columbia University Press.`,
  `Chhibber P. K. and R. Verma. 2018. Ideology and Identity: The Changing Party Systems of India. New York: Oxford University Press.`,
  `Choudhury, P. K. 2016. 'Role of Private Sector in Medical Education and Human Resource Development for Health in India'. Economic & Political Weekly 51(3): 71–79.`,
  `Coe, N. M., M. Hess, H. W. Yeung, P. Dicken and J. Henderson. 2004. '"Globalizing" Regional Development: A Global Production Networks Perspective'. Transactions of the Institute of British Geographers 29(4): 468–84.`,
  `Cornwell, E. Y. and B. Cornwell. 2008. 'Access to Expertise as a Form of Social Capital'. Sociological Perspectives 51(4): 853–76.`,
  `Crouch, C. and W. Streeck. 1997. 'Introduction: The Future of Capitalist Diversity'. In Political Economy of Modern Capitalism. London: Sage.`,
  `Cullen, W. J. 2019. A Comparative Analysis to Understand the Subnational Motivations for Renewable Energy Development in India. Claremont McKenna College.`,
  `Damodaran, H. 2008. India's New Capitalists: Caste, Business, and Industry in a Modern Nation. Basingstoke: Palgrave MacMillan.`,
  `———. 2016. 'How Tamil Nadu's Rural Industry Model Can Keep Farm Unrest at Bay'. Indian Express, 27 September.`,
  `Dasgupta, A. 2017. 'Land Reform in Kerala and West Bengal'. In The Land Question in India. Oxford University Press.`,
  `Das Gupta, M. 2005. 'Public Health in India: Dangerous Neglect'. Economic & Political Weekly 40(49): 5159–65.`,
  `Das Gupta, M. et al. 2010. 'How Might India's Public Health Systems be Strengthened? Lessons from Tamil Nadu'. Economic & Political Weekly 45(10): 46–60.`,
  `Datta, K. K. 2009. 'Public Health Workforce in India'. MoHFW (GoI) and WHO Country Office for India.`,
  `Davis, J. R. and D. J. Bezemer. 2004. The Development of the Rural Non-farm Economy in Developing Countries and Transition Economies. Chatham: Natural Resources Institute.`,
  `D'Costa, Anthony P. and A. Chakraborty (eds). 2019. Changing Contexts and Shifting Roles of the Indian State. Singapore: Springer.`,
  `De Silva, I. and S. Sumarto. 2015. 'Dynamics of Growth, Poverty and Human Capital'. Journal of Economic Development 40(2): 1–33.`,
  `Deshpande, A. and S. Sharma. 2013. 'Entrepreneurship or Survival? Caste and Gender of Small Business in India'. Economic & Political Weekly 48(28): 38–49.`,
  `Dholakia, A. R. and R. H. Dholakia. 2004. 'Expenditure Allocation and Welfare Returns to Government'. Economic & Political Weekly 39(24): 853–56.`,
  `Dorin, B. 2017. 'India and Africa in the Global Agricultural System (1960–2050)'. Economic & Political Weekly 52(25–26): 5–13.`,
  `Doval, N. 2017. 'Tamil Nadu's Amma Canteen Concept Catches On in Other States'. Livemint, 27 March.`,
  `Drèze, J. and A. Sen. 2013. An Uncertain Glory: India and Its Contradictions. Princeton University Press.`,
  `Drèze, J. and R. Khera. 2013. 'Rural Poverty and the Public Distribution System'. Economic & Political Weekly 48(45–46): 55–60.`,
  `———. 2012. 'Regional Patterns of Human and Child Deprivation in India'. Economic & Political Weekly 47(39): 42–49.`,
  `Drèze, J. 2006. 'Universalization with Quality: ICDS in a Rights Perspective'. Economic & Political Weekly 41(34): 3706–15.`,
  `Dubbudu, R. 2017. 'Karnataka, Tamil Nadu & Telangana Together Make Up for More than 60% of IT Exports'. Factly, 26 October.`,
  `Eaton, K. 2004. Politics beyond the Capital: The Design of Subnational Institutions in South America. Stanford University Press.`,
  `Evans, P. 1995. Embedded Autonomy: States and Industrial Transformation. Princeton: Princeton University Press.`,
  `Evans, P. and P. Heller. 2015. 'Human Development, State Transformation and the Politics of the Developmental State'. In The Oxford Handbook of Transformations of the State. Oxford University Press.`,
  `Ferguson, J. 2015. Give a Man a Fish: Reflections on the New Politics of Distribution. Durham: Duke University Press.`,
  `Fuller, C. J. and H. Narasimhan. 2014. Tamil Brahmans: The Making of a Middle-Class Caste. University of Chicago Press.`,
  `———. 2006. 'Engineering Colleges, "Exposure" and Information Technology Professionals in Tamil Nadu'. Economic & Political Weekly 41(3): 258–62, 288.`,
  `Galanter, M. 1984. Competing Equalities: Law and the Backward Classes in India. Berkeley: University of California Press.`,
  `Geetha, V. and S. V. Rajadurai. 2008. Towards a Non-Brahmin Millennium: From Iyothee Thass to Periyar, 2nd edn. Kolkata: Samya.`,
  `Ghani, E., A. G. Goswami and W. R. Kerr. 2012. 'Is India's Manufacturing Sector Moving Away from Cities?' (WP No. 12-090). Harvard Business School.`,
  `Ghosh, M. 2012. 'Regional Economic Growth and Inequality in India during the Pre- and Post-reform Periods'. Oxford Development Studies 40(2): 190–212.`,
  `Gorringe, H. 2017. Panthers in Parliament: Dalits, Caste, and Political Power in South India. New Delhi: Oxford University Press.`,
  `Government of India. 2014. Annual Survey of Industries, 2014. New Delhi: Central Statistics Office, MoSPI.`,
  `Government of India. 2017–18. All India Survey on Higher Education. New Delhi: Department of Higher Education, MHRD.`,
  `Government of India. 2018. Periodic Labour Force Survey 2018. New Delhi: MoSPI.`,
  `Government of Tamil Nadu. 1993. Tamil Nadu: An Economic Appraisal 1992-93. Madras: Department of Evaluation and Applied Research.`,
  `Government of Tamil Nadu. 2017. Tamil Nadu Human Development Report. New Delhi: Academic Foundation.`,
  `Goyal, J. and D. P. Singh. 2014. 'Academic Performance of OBC Students in Universities'. Economic & Political Weekly 49(5): 55–62.`,
  `Guhan, S. and J. P. Mencher. 1983. 'Iruvelpattu Revisited: I & II'. Economic & Political Weekly 18(23–24).`,
  `Hardgrave, R. L. 1969. The Nadars of Tamilnad: The Political Culture of a Community in Change. University of California Press.`,
  `Harriss, J. 1999. 'Comparing Political Regimes Across Indian States: A Preliminary Essay'. Economic & Political Weekly 34(48): 3367–77.`,
  `Harriss, J. and A. K. J. Wyatt. 2019. 'Business and Politics: The Tamil Nadu Puzzle'. In Business and Politics in India. New York: Oxford University Press.`,
  `Harriss, J., J. Jeyaranjan and K. Nagaraj. 2010. 'Land, Labour and Caste Politics in Rural Tamil Nadu in the 20th Century: Iruvelpattu 1916–2008'. Economic & Political Weekly 45(31): 47–61.`,
  `Harriss-White, B. 2001. India Working: Essays on Society and Economy. Cambridge University Press.`,
  `Harriss-White, B. et al. 2013. Dalits and Adivasis in India's Business Economy: Three Essays and an Atlas. Gurgaon: Three Essays Collective.`,
  `Harvey, D. 2005. Spaces of Neoliberalization: Towards a Theory of Uneven Geographical Development. Stuttgart: Franz Steiner Verlag.`,
  `Hasan, R., S. Lamba and A. Sen Gupta. 2013. 'Growth, Structural Change and Poverty Reduction'. In Labour, Employment and Economic Growth in India. Cambridge University Press.`,
  `Heller, P. 1999. The Labor of Development: Workers and the Transformation of Capitalism in Kerala, India. Ithaca: Cornell University Press.`,
  `Heyer, J. 2016. 'Rural Gounders on the Move in Western Tamil Nadu: 1981–2 to 2008–9'. In The Changing Village in India. Oxford University Press.`,
  `Hodges, S. 2013. '"It All Changed after Apollo": Healthcare Myths and Their Making in Contemporary India'. Indian Journal of Medical Ethics 10(4): 242–49.`,
  `Indo Asian News Service. 2018. 'Kerala Tops Governance Index, Tamil Nadu Ranks Second: Report'. Hindustan Times, 22 July.`,
  `Irschick, E. F. 1969. Politics and Social Conflict in South India: The Non-Brahman Movement and Tamil Separatism, 1916–1929. University of California Press.`,
  `Iyer, L., T. Khanna and A. Varshney. 2013. 'Caste and Entrepreneurship in India'. Economic & Political Weekly 48(6): 52–60.`,
  `Jaffrelot, C. and A. Kalaiyarasan. 2019. 'Most Marginalised of Them All'. Indian Express, 1 November.`,
  `Jaffrelot, C. 2000. 'The Rise of the Other Backward Classes in the Hindi Belt'. Journal of Asian Studies 59(1): 86–108.`,
  `Jeffery, R. 1988. The Politics of Health in India. Berkeley: University of California Press.`,
  `Jenkins, R. 2004. Regional Reflections: Comparing Politics Across India's States. New Delhi: Oxford University Press.`,
  `Jeyaranjan, J. 2011. 'Women and Pro-poor Policies in Rural Tamil Nadu'. Economic & Political Weekly 46(43): 64–74.`,
  `———. 2019. 'Sand and the Politics of Plunder in Tamil Nadu'. In The Wild East: Criminal Political Economies in South Asia. London: UCL Press.`,
  `———. 2020. 'Tenancy Reforms in Tamil Nadu: A Study from the Cauvery Delta Region'. In Rethinking Social Justice. Hyderabad: Orient Blackswan.`,
  `Joshi, D. K. and K. McGrath. 2015. 'Political Ideology, Public Policy and Human Development in India: Explaining the Gap between Gujarat and Tamil Nadu'. Journal of Contemporary Asia 45(3): 465–89.`,
  `Kabeer, N. 2012. 'Women's Economic Empowerment and Inclusive Growth' (Discussion Paper No. 29/12). CDPR, SOAS.`,
  `Kailash, K. K. and M. Rasaratnam. 2015. 'The Policy-Shaping Capacity of States: Publicly Funded Health Insurance in Tamil Nadu and Kerala'. In Politics of Welfare. Oxford University Press.`,
  `Kalaiyarasan, A. 2014. 'A Comparison of Developmental Outcomes in Gujarat and Tamil Nadu'. Economic & Political Weekly 49(15): 55–63.`,
  `———. 2017. 'NEET Could Undo Tamil Nadu's Achievements in Public Health'. Economic & Political Weekly 52(38).`,
  `———. 2017. 'Populism and Party Society: Development Regimes in Tamil Nadu and West Bengal'. In Political Economy of Contemporary India. Cambridge University Press.`,
  `———. 2020. 'Structural Change in Tamil Nadu, 1980–2010: Limits of Subnational Development' (Working Paper). Madras Institute of Development Studies.`,
  `Kannan, R. 2017. Anna: The Life and Times of C. N. Annadurai. New Delhi: Penguin.`,
  `Kapur, D. 2010. 'Indian Higher Education'. In American Universities in a Global Market. University of Chicago Press.`,
  `Kapur, D. and P. B. Mehta. 2007. 'Mortgaging the Future'. India International Centre Quarterly 34(3/4): 154–66.`,
  `Kar, S. and S. Sakthivel. 2007. 'Reforms and Regional Inequality in India'. Economic & Political Weekly 42(47).`,
  `Keating, M. 2013. Rescaling the European State. Oxford University Press.`,
  `Kennedy, L. 2014. The Politics of Economic Restructuring in India. London and New York: Routledge.`,
  `Khera, R. 2011. 'Trends in Diversion of Grain from the Public Distribution System'. Economic & Political Weekly 46(21): 106–14.`,
  `———. 2011. 'Revival of the Public Distribution System: Evidence and Explanations'. Economic & Political Weekly 46(44–45): 36–50.`,
  `Kochhar, K. et al. 2006. 'India's Pattern of Development: What Happened, What Follows?' (WP/06/22). International Monetary Fund.`,
  `Kohli, A. 2012. Poverty Amidst Plenty in the New India. Cambridge University Press.`,
  `Kumar, A. S. et al. 2011. 'Financing Health Care for All: Challenges and Opportunities'. The Lancet 377(9766): 668–79.`,
  `Kumaradoss, Y. V. 2004. 'Kamaraj Remembered'. Economic & Political Weekly 39(17): 1655–57.`,
  `Laclau, E. 2005. On Populist Reason. London and New York: Verso.`,
  `Laclau, E. and C. Mouffe. 2014. Hegemony and Socialist Strategy, 2nd edn. London: Verso.`,
  `Lakshman, N. 2011. Patrons of the Poor: Caste Politics and Policymaking in India. New Delhi: Oxford University Press.`,
  `Lalitha, N. 2008. 'Tamil Nadu Government Intervention and Prices of Medicines'. Economic & Political Weekly 43(1): 66–71.`,
  `Lanjouw, J. O. and P. Lanjouw. 2001. 'The Rural Non-farm Sector: Issues and Evidence from Developing Countries'. Agricultural Economics 26(1): 1–23.`,
  `Lewis, A. 1954. 'Economic Development with Unlimited Supplies of Labour'. The Manchester School 22: 139–91.`,
  `Madras Institute of Development Studies. 1988. Tamil Nadu Economy: Performance and Issues. New Delhi: Oxford and IBH.`,
  `Mahadevan, R. 1978. 'Immigrant Entrepreneurs in Colonial Burma: Nattukottai Chettiars of Tamil Nadu, 1880–1930'. Indian Economic and Social History Review 15(3): 329–58.`,
  `Mahadevan, R. and M. Vijayabaskar. 2014. 'Understanding the Making of Non-corporate Capital: Entrepreneurial Narratives from Tiruppur, Tamil Nadu' (Occasional Paper No. 33). NMML.`,
  `Manoharan, K. R. 2020. 'In the Path of Ambedkar: Periyar and the Dalit Question'. South Asian History and Culture 11(2): 1–14.`,
  `Mehrotra, S. 2006. 'Well-being and Caste in Uttar Pradesh: Why UP Is Not Like Tamil Nadu'. Economic & Political Weekly 41(40): 4261–71.`,
  `Mehrotra, S. et al. 2014. 'Explaining Employment Trends in the Indian Economy: 1993–94 to 2011–12'. Economic & Political Weekly 49(32): 49–57.`,
  `Mencher, J. P. 1975. 'Land Ceilings in Tamil Nadu: Facts and Fictions'. Economic & Political Weekly 10(5/7).`,
  `Ministry of Finance. 2018. Economic Survey 2017–18, Vol. 1. New Delhi: Government of India.`,
  `Mundle, S., S. Chowdhury and S. Sikdar. 2016. 'Governance Performance of Indian States'. Economic & Political Weekly 51(36): 55–64.`,
  `Munshi, K. 2014. 'Community Networks and the Process of Development'. Journal of Economic Perspectives 28(4): 49–76.`,
  `Muraleedharan, V. R. 1992. 'Professionalising Medical Practice in Colonial South India'. Economic & Political Weekly 27(4).`,
  `Nagaraj, K. 2006. 'Tamil Nadu Economy: Contours of Change: A Secondary Data Exploration'. Madras Institute of Development Studies.`,
  `Nagaraj, R. and S. Pandey. 2013. 'Have Gujarat and Bihar Outperformed the Rest of India? A Statistical Note'. Economic & Political Weekly 48(39): 39–41.`,
  `Naidu, T. V. (ed.). 2010 [1932]. The Justice Movement: 1917. Madras: Dravidar Kazhagam.`,
  `Naig, U. 2015. 'Tamil Nadu Has Most Number of Dalit Entrepreneurs'. The Hindu, 21 September.`,
  `Narayan, S. 2018. The Dravidian Years: Politics and Welfare in Tamil Nadu. New Delhi: Oxford University Press.`,
  `National Commission for Enterprises in the Unorganised Sector (NCEUS). 2009. Report of the NCEUS, Vol. 1. New Delhi: Academic Foundation.`,
  `National Sample Survey Office. 2016. Education in India (Report No. 575). NSS 71st round. New Delhi: MoSPI.`,
  `Omvedt, G. 2011. Understanding Caste: From Buddha to Ambedkar and Beyond. Hyderabad: Orient Blackswan.`,
  `Pandian, M. S. S. 1994. 'Notes on the Transformation of "Dravidian" Ideology: Tamil Nadu, c. 1900–1940'. Social Scientist 22(5–6): 84–104.`,
  `———. 2007. Brahmin and Non-Brahmin: Genealogies of the Tamil Political Present. Ranikhet: Permanent Black.`,
  `———. 2013. 'Caste in Tamil Nadu-II: Slipping Hegemony of Intermediate Castes'. Economic & Political Weekly 48(4): 13–15.`,
  `Periyar. 1992 [1926]. 'Pirappurimayum Thadigaluni'. In V. Anaimuthu (ed.), Periyar E V R Sinthanaigal, Vol. 1.`,
  `Piketty, T. 2020. Capital and Ideology. Cambridge: Harvard University Press.`,
  `Prabhu, K. S. 2007. 'Social Sectors during Economic Reforms: The Indian Experience'. Oxford Development Studies 27(2): 187–210.`,
  `Rajadurai, S. V. and V. Geetha. 2009. Periyar: Suyamariyadhai samadharmam, expanded edn. Coimbatore: Vidiyal Pathippagam.`,
  `Rao, M. et al. 2011. 'Human Resources for Health in India'. The Lancet 377(9765): 587–98.`,
  `Rao, S. 2017. Do We Care: India's Health System. New Delhi: Oxford University Press.`,
  `Rosanvallon, P. 2008. Counter-Democracy: Politics in an Age of Distrust. Cambridge University Press.`,
  `Rothboeck, S., M. Vijayabaskar and V. Gayathri. 2001. Labour in The New Economy: The Case of The Indian Software Industry. New Delhi: ILO.`,
  `Rukmani, R. 1994. 'Urbanisation and Socio-economic Change in Tamil Nadu, 1901–91'. Economic & Political Weekly 29(51–52): 3263–72.`,
  `Sample Registration System (SRS). 'Compendium of India's Fertility and Mortality Indicators, 1971–2013'. Ministry of Home Affairs, Government of India.`,
  `Sanyal, K. 2007. Rethinking Capitalist Development: Primitive Accumulation, Governmentality and Post-colonial Capitalism. New Delhi: Routledge.`,
  `Sattanathan, A. N. 2007. Plain Speaking: A Sudra's Story. New Delhi: Permanent Black.`,
  `Selvaraj, S., D. Abrol and K. M. Gopakumar. 2014. Access to Medicines in India. New Delhi: Academic Foundation.`,
  `Sennett, R. 2012. Together: The Rituals, Pleasures and Politics of Cooperation. New Haven and London: Yale University Press.`,
  `Shyam Sundar, K. R. 2009. 'The Current State of Industrial Relations in Tamil Nadu'. ILO Asia–Pacific Working Paper Series.`,
  `Singh, Pritam. 2008. Federalism, Nationalism and Development: India and the Punjab Economy. Oxon: Routledge.`,
  `Singh, Prerna. 2015. How Solidarity Works for Welfare: Subnationalism and Social Development in India. Cambridge University Press.`,
  `Singh, S. K. 2000. 'Productive Efficiency Across Firms: State Road Transport Undertakings'. Economic & Political Weekly 35(48): 4269–75.`,
  `Sinha, A. 2003. 'Rethinking the Developmental State Model: Divided Leviathan and Subnational Comparisons in India'. Comparative Politics 35(4): 459–76.`,
  `———. 2006. The Regional Roots of Developmental Politics in India: A Divided Leviathan. New Delhi: Oxford University Press.`,
  `Sinha, D. 2016. Women, Health and Public Services in India: Why Are States Different. New Delhi: Routledge.`,
  `Slater, G. 1918. Some South Indian Villages. Oxford: Oxford University Press.`,
  `Snyder, R. 2001. 'Scaling Down: The Subnational Comparative Method'. Studies in Comparative International Development 36(1): 93–110.`,
  `Spratt, P. 1970. D.M.K in Power. Bombay: Nachiketa Publications.`,
  `Srinivasan, V. 2010. 'Understanding Public Services in Tamil Nadu: An Institutional Perspective'. Doctoral dissertation, University of Syracuse.`,
  `Subramanian, V. 1999. Ethnicity and Populist Mobilization: Political Parties, Citizens, and Democracy in South India. New York: Oxford University Press.`,
  `Sud, N. 2012. Liberalization, Hindu Nationalism and the State: A Biography of Gujarat. New York: Oxford University Press.`,
  `Suntharalingam, R. 1980. Politics and Nationalist Awakening in South India, 1852–1891. New Delhi and Jaipur: Rawat.`,
  `Swaminathan, P. 1994. 'Where Are the Entrepreneurs? What the Data Reveal for Tamil Nadu'. Economic & Political Weekly 29(22): M64–M74.`,
  `Swamy, Arun R. 1998. 'Parties, Political Identities and the Absence of Mass Political Violence in South India'. In Community Conflicts and the State in India. Oxford University Press.`,
  `Tilly, C. 1998. 'How to Hoard Opportunities'. In Durable Inequality. University of California Press.`,
  `Trautmann, T. R. 2006. Languages and Nations: The Dravidian Proof in Colonial Madras. New Delhi: Yoda Press.`,
  `Tyabji, N. 1988. 'State Aid to Industry: Madras 1921–37'. Economic & Political Weekly 23(31).`,
  `Upadhya, C. 2007. 'Employment, Exclusion and "Merit" in the Indian IT Industry'. Economic & Political Weekly 42(20): 1863–68.`,
  `Vaidyanathan, G. 2014. 'How Has Tamil Nadu Fared under NRHM'. In India Social Development Report 2014: Challenges of Public Health. Oxford University Press.`,
  `Varshney, A. 1995. Democracy, Development, and the Countryside: Urban-Rural Struggles in India. Cambridge University Press.`,
  `Venkatachalapathy, A. R. 1995. 'Dravidian Movement and Saivites: 1927–1944'. Economic & Political Weekly 30(14): 761–68.`,
  `Venkatasubramanian, A. K. 2006. 'The Political Economy of the Public Distribution System in Tamil Nadu'. In Reinventing Public Service Delivery in India. New Delhi: Sage.`,
  `Vijayabaskar, M. 2017. 'The Agrarian Question amidst Popular Welfare: Interpreting Tamil Nadu's Emerging Rural Economy'. Economic & Political Weekly 52(46): 67–72.`,
  `Vijayabaskar, M. and A. Kalaiyarasan. 2014. 'Caste as Social Capital: The Tiruppur Story'. Economic & Political Weekly 49(10): 34–38.`,
  `Vijayabaskar, M. and G. Balagopal. 2019. 'Politics of Poverty Alleviation Strategies in India' (WP 2019-7). UNRISD.`,
  `Vivek, S. 2014. Delivering Public Services Effectively: Tamil Nadu and Beyond. New Delhi: Oxford University Press.`,
  `Wade, R. 1990. Governing the Market: Economic Theory and the Role of Government in East Asian Industrialization. Princeton University Press.`,
  `Washbrook, D. A. 1977. The Emergence of Provincial Politics: The Madras Presidency 1870–1920. New Delhi: Vikas.`,
  `Weiner, M. 1990. The Child and the State in India: Child Labor and Education Policy in Comparative Perspective. Princeton University Press.`,
  `Witsoe, J. 2013. Democracy Against Development: Lower-Caste Politics and Political Modernity in Postcolonial India. University of Chicago Press.`,
  `World Bank. 2009. Reshaping Economic Geography: World Development Report. Washington DC.`,
  `Wyatt, A. K. J. 2013. 'Combining Clientelist and Programmatic Politics in Tamil Nadu, South India'. Commonwealth and Comparative Politics 51(1): 27–55.`,
  `———. 2013. 'Populism and Politics in Contemporary Tamil Nadu'. Contemporary South Asia 21(4): 365–81.`,
];
